version: '3'

services:
  config-server-app-container:
    image: younesschafia/config-server-app-image
    container_name: config-server-app-container
    volumes:
      - c:/tmp:/data
    networks:
      - api-home-app-mysql
    ports:
      - 8888:8888
  mysqldb-home-app:
    image: mysql:8
    container_name: mysqldb-home-app
    volumes:
      - c:/tmp:/data
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=springboot-tuto
    networks:
      - api-home-app-mysql
  gateway-api-home-app-container:
    image: younesschafia/gateway-api-home-app-image:2.3
    container_name: gateway-api-home-app-container
    volumes:
      - c:/tmp:/data
    depends_on:
      - mysqldb-home-app
    links:
      - config-server-app-container
    networks:
      - api-home-app-mysql
    ports:
      - 8080:8080
networks:
  api-home-app-mysql:

volumes:
  data: